### ISSUE TITLE
how to hide logging calls

### ISSUE THREAD

**Issue by dpinol** [aviatesk/JETTest.jl#11]
Hi,
is there any workaround to hide the @debug calls from the reports? In this case, the reported function handle_message will not be actually executed because it's not executed with debug logging level.

thanks

```
module M
       f()=@debug "hj"
end

@report_dispatch frame_filter=sv->sv.mod===M M.f()
═════ 1 possible error found ═════
┌ @ logging.jl:310 Base.CoreLogging.handle_message(%24, %1, %25, %26, %27, %28, %29, %30)
│ runtime dispatch detected: Base.CoreLogging.handle_message(%24::Base.CoreLogging.AbstractLogger, %1::Base.CoreLogging.LogLevel, %25::String, %26::Module, %27::Symbol, %28::Symbol, %29::String, %30::Int64)
└──────────────────
```

**Comment by dpinol** [comment]
I found the way
```
 myfunction_filter(@nospecialize(ft)) = ft !== typeof(Logging.handle_message)
@report_dispatch frame_filter=sv->sv.mod===M function_filter=myfunction_filter  M.f()
```

**Comment by aviatesk** [comment]
You can use `function_filter` configuration like: https://github.com/aviatesk/JET.jl/blob/89544c229ef7c6021c0996b38dc9c84880d17f6c/test/runtests.jl#L89

Also, if you're on v1.7 and higher, please checkout to the latest master of JET.jl and use `@report_opt`.
I will deprecate this package once v1.7 is out, and latest JET.jl implements much better functionalities (for optimization analysis, you can refer to https://aviatesk.github.io/JET.jl/dev/optanalysis/)
